name: Linting

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: Dependency Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry
        run: pipx install poetry
      - name: Install
        run: poetry install
      - name: isort
        run: poetry run isort --check .
        continue-on-error: true
      - name: Black
        run: poetry run black --check .
        continue-on-error: true
      - name: Tests
        run: poetry run coverage run -m pytest
      - name: Coverage
        run: poetry run coverage report
