name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v5

      - name: Setup Python
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install uv
        if: ${{ steps.release.outputs.releases_created }}
        uses: astral-sh/setup-uv@v7

      - name: Cache the virtualenv
        uses: actions/cache@v5
        if: ${{ steps.release.outputs.releases_created }}
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/uv.lock') }}

      - name: Build
        if: ${{ steps.release.outputs.releases_created }}
        run: uv build

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ steps.release.outputs.tag_name }} dist/*.whl
